name: Release (Preview)

on:
  push:
    branches: [ "main" ]
    
jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --environment "SVEVE:USERNAME=${{ secrets.SVEVE_USERNAME }}" --environment "SVEVE:PASSWORD=${{ secrets.SVEVE_PASSWORD }}"
    - name: Pack
      run: dotnet pack --no-build --configuration Release --output ./artifacts --version-suffix "preview"
    - name: Publish
      run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/MatsM16/index.json"